language: node_js
sudo: false
node_js:
  - "6"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn lint
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  fqdn: ysitd.cloud
  on:
    branch: master
